# Generated by Django 4.2 on 2025-04-13 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import golshani.extra_func


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0005_alter_returnperiod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='تلفن ثابت')),
                ('gender', models.CharField(blank=True, choices=[('MAN', 'آقا'), ('WOMAN', 'خانوم')], max_length=6, verbose_name='جنسیت')),
                ('chtype', models.CharField(blank=True, choices=[('PERSONAL', 'حقیقی'), ('CORPRATE', 'حقوقی')], max_length=10, verbose_name='شخصیت')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('province', models.CharField(max_length=30, verbose_name='استان')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('postal_code', models.PositiveBigIntegerField(null=True, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('code_meli', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('jalali_birth', models.CharField(max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('application_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('pending_user', 'تکمیل اطلاعات'), ('upload_documents', 'بارگذاری مدارک'), ('pay_fee', 'پرداخت فیش'), ('under_review', 'بررسی مدارک'), ('rejected', 'رد شده'), ('approved', 'تایید شده')], default='pending_user', max_length=20)),
                ('loan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='managements.loantype', verbose_name='مقدار تحصیلات')),
                ('return_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='managements.returnperiod', verbose_name='دوره بازپرداخت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'حساب مشتریان',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_meli', models.ImageField(upload_to=golshani.extra_func.user_directory_path, validators=[django.core.validators.validate_image_file_extension, golshani.extra_func.validate_image_file])),
                ('shenas_name', models.ImageField(upload_to=golshani.extra_func.user_directory_path, validators=[django.core.validators.validate_image_file_extension, golshani.extra_func.validate_image_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(default='****', max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.account')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
