# Generated by Django 4.2 on 2025-05-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='return_period',
        ),
    ]
