# Generated by Django 4.2 on 2025-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('pending_user', 'تکمیل اطلاعات'), ('upload_documents', 'بارگذاری مدارک'), ('pay_fee', 'پرداخت فیش'), ('under_review', 'بررسی مدارک'), ('rejected', 'رد شده'), ('complete_payment', 'تکمیل وجه'), ('approved', 'تایید شده')], default='pending_user', max_length=20),
        ),
    ]
