# Generated by Django 4.2 on 2025-05-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FEE', 'فیش'), ('COMPLETE', 'تکمیل وجه')], max_length=10, verbose_name='علت پرداخت'),
        ),
    ]
