# Generated by Django 4.2 on 2025-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FEE', 'فیش'), ('COMPLETE', 'تکمیل وجه')], default='FEE', max_length=10, verbose_name='علت پرداخت'),
        ),
    ]
