# Generated by Django 4.2 on 2025-05-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='application_date',
        ),
    ]
