# Generated by Django 4.2 on 2025-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='title',
            field=models.IntegerField(verbose_name='مقدار وام به تومان'),
        ),
    ]
