# Generated by Django 4.2 on 2025-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_alter_loantype_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('user_message', models.TextField(verbose_name='پیام')),
                ('send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ارسال')),
                ('seen', models.BooleanField(default=False, verbose_name='مشاهده شد؟')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
