# Generated by Django 5.1.7 on 2025-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='1', verbose_name='پاسخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.TextField(default='1', verbose_name='سوال'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FaqItems',
        ),
    ]
