# Generated by Django 4.2 on 2025-04-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_remove_faq_title_faq_answer_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnperiod',
            options={'verbose_name': 'دوره بازپرداخت', 'verbose_name_plural': 'دوره بازپرداخت'},
        ),
    ]
