# Generated by Django 4.2 on 2025-05-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_loan_type_and_more'),
        ('managements', '0005_alter_returnperiod_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnperiod',
            name='loan_type',
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
        migrations.DeleteModel(
            name='ReturnPeriod',
        ),
    ]
