# Generated by Django 4.2 on 2025-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_remove_returnperiod_loan_type_delete_loantype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='همراه')),
                ('whatsapp', models.PositiveIntegerField(blank=True, null=True, verbose_name='واتساپ')),
                ('instagram', models.CharField(blank=True, max_length=30, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=30, null=True, verbose_name='ایدی_تلگرام')),
                ('twitter', models.CharField(blank=True, max_length=30, null=True, verbose_name='توییتر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'مشخصات سایت',
                'verbose_name_plural': 'مشخصات سایت',
            },
        ),
    ]
