# Generated by Django 4.2 on 2025-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_staticdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ایمیل'),
        ),
    ]
